country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [335, 690, 456, 805],
                "x": 395,
                "y": 799,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [942, 543, 1060, 652],
                "x": 1000,
                "y": 647,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [392, 691, 509, 798],
                "x": 456,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-55, 180, 53, 277],
                "x": 0,
                "y": 286,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 1000, "y": 460, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [-65, 279, 54, 374],
                "x": 0,
                "y": 375,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [948, 585, 1066, 670],
                "x": 1000,
                "y": 677,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [946, 684, 1058, 787],
                "x": 1000,
                "y": 789,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [451, -106, 575, -4],
                "x": 506,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [946, 252, 1060, 359],
                "x": 1000,
                "y": 356,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [340, 624, 474, 719],
                "x": 405,
                "y": 718,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [941, 523, 1054, 624],
                "x": 997,
                "y": 624,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [391, 639, 515, 742],
                "x": 461,
                "y": 734,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [-7, 225, 109, 320],
                "x": 43,
                "y": 316,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [888, 268, 1007, 374],
                "x": 947,
                "y": 367,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-39, 308, 78, 400],
                "x": 19,
                "y": 402,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 978, "y": 623, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [925, 615, 1034, 707],
                "x": 979,
                "y": 715,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [454, -2, 579, 102],
                "x": 523,
                "y": 95,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [903, 332, 1025, 437],
                "x": 966,
                "y": 434,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [360, 541, 479, 639],
                "x": 415,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [935, 495, 1057, 597],
                "x": 995,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [401, 561, 537, 662],
                "x": 467,
                "y": 671,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [23, 238, 143, 352],
                "x": 86,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [830, 210, 951, 316],
                "x": 894,
                "y": 307,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [-19, 332, 108, 436],
                "x": 38,
                "y": 426,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [894, 474, 1027, 578],
                "x": 957,
                "y": 575,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [890, 542, 1010, 654],
                "x": 959,
                "y": 649,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [479, 77, 609, 188],
                "x": 540,
                "y": 180,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [870, 392, 984, 501],
                "x": 933,
                "y": 502,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [363, 466, 480, 564],
                "x": 425,
                "y": 572,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 992, "y": 579, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [406, 502, 543, 619],
                "x": 473,
                "y": 612,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [64, 254, 198, 363],
                "x": 130,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [792, 178, 897, 275],
                "x": 842,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [1, 355, 113, 442],
                "x": 57,
                "y": 446,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [876, 442, 1004, 526],
                "x": 936,
                "y": 534,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [878, 496, 1007, 598],
                "x": 938,
                "y": 590,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [496, 164, 627, 254],
                "x": 557,
                "y": 255,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [850, 456, 966, 553],
                "x": 900,
                "y": 560,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [373, 398, 488, 517],
                "x": 435,
                "y": 507,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [933, 452, 1041, 548],
                "x": 990,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [415, 458, 543, 547],
                "x": 478,
                "y": 557,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [114, 276, 231, 385],
                "x": 173,
                "y": 383,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [737, 154, 855, 266],
                "x": 789,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [18, 361, 132, 460],
                "x": 76,
                "y": 463,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 914, "y": 498, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [851, 441, 968, 547],
                "x": 918,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [506, 222, 638, 329],
                "x": 574,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [797, 516, 922, 604],
                "x": 866,
                "y": 609,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [384, 339, 505, 451],
                "x": 445,
                "y": 447,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [930, 433, 1043, 535],
                "x": 988,
                "y": 536,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [423, 406, 536, 500],
                "x": 484,
                "y": 506,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [150, 289, 282, 396],
                "x": 217,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [683, 167, 800, 278],
                "x": 736,
                "y": 273,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [30, 367, 164, 474],
                "x": 95,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [843, 360, 948, 472],
                "x": 893,
                "y": 469,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [838, 392, 951, 488],
                "x": 897,
                "y": 492,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [526, 283, 658, 386],
                "x": 591,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [783, 540, 888, 645],
                "x": 833,
                "y": 649,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [404, 291, 516, 390],
                "x": 456,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [930, 423, 1048, 524],
                "x": 985,
                "y": 516,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [423, 362, 558, 458],
                "x": 490,
                "y": 461,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [202, 310, 313, 407],
                "x": 260,
                "y": 411,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [616, 200, 751, 303],
                "x": 684,
                "y": 299,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [48, 381, 172, 482],
                "x": 114,
                "y": 488,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [818, 344, 931, 435],
                "x": 872,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [809, 346, 943, 445],
                "x": 877,
                "y": 453,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [556, 315, 672, 415],
                "x": 608,
                "y": 425,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 800, "y": 681, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [400, 247, 518, 333],
                "x": 466,
                "y": 342,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [921, 388, 1047, 492],
                "x": 983,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [431, 321, 548, 427],
                "x": 496,
                "y": 422,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [237, 315, 359, 429],
                "x": 304,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [573, 243, 688, 338],
                "x": 631,
                "y": 336,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [73, 395, 199, 490],
                "x": 133,
                "y": 496,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [799, 325, 917, 421],
                "x": 851,
                "y": 426,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [790, 330, 912, 428],
                "x": 857,
                "y": 420,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [558, 373, 679, 456],
                "x": 625,
                "y": 465,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [704, 611, 831, 710],
                "x": 766,
                "y": 706,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [406, 189, 545, 301],
                "x": 476,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [929, 375, 1036, 465],
                "x": 981,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [440, 284, 564, 386],
                "x": 501,
                "y": 389,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [293, 325, 406, 437],
                "x": 347,
                "y": 427,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [509, 286, 643, 385],
                "x": 578,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [99, 407, 216, 499],
                "x": 152,
                "y": 501,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [773, 311, 886, 403],
                "x": 829,
                "y": 412,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [775, 282, 905, 392],
                "x": 836,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [583, 406, 696, 493],
                "x": 642,
                "y": 498,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [678, 616, 798, 716],
                "x": 733,
                "y": 723,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [434, 158, 547, 253],
                "x": 486,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [922, 361, 1028, 465],
                "x": 978,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [453, 257, 569, 371],
                "x": 507,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [329, 325, 443, 437],
                "x": 391,
                "y": 432,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [458, 323, 592, 431],
                "x": 526,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [112, 393, 224, 504],
                "x": 171,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [745, 294, 866, 411],
                "x": 808,
                "y": 402,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [747, 268, 867, 368],
                "x": 816,
                "y": 370,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [606, 434, 723, 520],
                "x": 659,
                "y": 524,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [631, 631, 759, 742],
                "x": 700,
                "y": 734,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [443, 133, 552, 233],
                "x": 496,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [913, 338, 1028, 439],
                "x": 976,
                "y": 437,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [461, 241, 574, 346],
                "x": 513,
                "y": 345,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [374, 338, 497, 431],
                "x": 434,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [410, 387, 536, 488],
                "x": 473,
                "y": 481,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [120, 404, 242, 506],
                "x": 190,
                "y": 503,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [728, 302, 845, 397],
                "x": 787,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [743, 253, 853, 354],
                "x": 795,
                "y": 354,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [608, 452, 738, 541],
                "x": 676,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [614, 644, 725, 747],
                "x": 666,
                "y": 738,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [445, 100, 570, 188],
                "x": 507,
                "y": 193,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [905, 328, 1034, 417],
                "x": 974,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [465, 239, 570, 343],
                "x": 518,
                "y": 335,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [417, 344, 540, 438],
                "x": 478,
                "y": 434,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [371, 417, 486, 523],
                "x": 421,
                "y": 527,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [146, 402, 270, 504],
                "x": 210,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [704, 291, 829, 400],
                "x": 765,
                "y": 394,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 775, "y": 341, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [628, 451, 749, 552],
                "x": 693,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [579, 642, 702, 734],
                "x": 633,
                "y": 737,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [458, 58, 573, 157],
                "x": 517,
                "y": 167,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [906, 291, 1030, 394],
                "x": 971,
                "y": 400,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [460, 244, 574, 330],
                "x": 524,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [457, 324, 586, 434],
                "x": 521,
                "y": 433,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [307, 464, 421, 571],
                "x": 368,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [166, 395, 292, 497],
                "x": 229,
                "y": 495,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [682, 289, 801, 403],
                "x": 744,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [695, 227, 808, 329],
                "x": 755,
                "y": 334,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 710, "y": 570, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [535, 632, 668, 726],
                "x": 600,
                "y": 731,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [465, 56, 577, 155],
                "x": 527,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [903, 272, 1020, 390],
                "x": 969,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [480, 248, 599, 350],
                "x": 530,
                "y": 341,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [512, 328, 615, 432],
                "x": 565,
                "y": 430,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [263, 494, 380, 596],
                "x": 315,
                "y": 593,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [180, 390, 303, 483],
                "x": 248,
                "y": 488,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [668, 298, 773, 394],
                "x": 723,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [667, 228, 799, 322],
                "x": 734,
                "y": 330,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [658, 486, 794, 583],
                "x": 727,
                "y": 576,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 566, "y": 721, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [479, 37, 599, 126],
                "x": 537,
                "y": 130,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [899, 268, 1033, 367],
                "x": 967,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [485, 269, 599, 360],
                "x": 536,
                "y": 359,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [547, 334, 660, 422],
                "x": 608,
                "y": 426,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [193, 506, 321, 599],
                "x": 263,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [201, 384, 318, 476],
                "x": 267,
                "y": 479,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [634, 317, 755, 404],
                "x": 702,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [655, 234, 780, 330],
                "x": 714,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [681, 473, 804, 569],
                "x": 744,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [463, 603, 588, 698],
                "x": 533,
                "y": 706,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [487, 13, 604, 109],
                "x": 547,
                "y": 118,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [898, 247, 1025, 354],
                "x": 964,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [473, 287, 594, 380],
                "x": 541,
                "y": 386,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [599, 312, 712, 411],
                "x": 652,
                "y": 421,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [155, 487, 279, 596],
                "x": 210,
                "y": 597,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [225, 376, 344, 459],
                "x": 286,
                "y": 468,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [614, 311, 750, 420],
                "x": 680,
                "y": 418,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [629, 241, 754, 329],
                "x": 693,
                "y": 334,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [703, 487, 819, 568],
                "x": 761,
                "y": 578,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [434, 597, 569, 684],
                "x": 499,
                "y": 689,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [501, 15, 620, 114],
                "x": 558,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [892, 225, 1017, 338],
                "x": 962,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [489, 320, 616, 434],
                "x": 547,
                "y": 425,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [641, 324, 759, 408],
                "x": 695,
                "y": 415,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [89, 472, 217, 573],
                "x": 157,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [249, 364, 373, 465],
                "x": 305,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [589, 329, 718, 441],
                "x": 659,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [619, 243, 739, 332],
                "x": 673,
                "y": 341,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 778, "y": 575, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [399, 569, 518, 671],
                "x": 466,
                "y": 668,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [511, 11, 636, 100],
                "x": 568,
                "y": 106,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [893, 221, 1016, 318],
                "x": 959,
                "y": 314,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [484, 378, 612, 483],
                "x": 553,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [672, 304, 804, 411],
                "x": 739,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [44, 404, 173, 511],
                "x": 105,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [254, 350, 376, 432],
                "x": 324,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [586, 352, 702, 451],
                "x": 638,
                "y": 445,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [591, 258, 715, 342],
                "x": 653,
                "y": 351,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [729, 467, 851, 568],
                "x": 795,
                "y": 571,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [380, 553, 493, 640],
                "x": 433,
                "y": 644,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [528, -2, 636, 100],
                "x": 578,
                "y": 107,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [904, 208, 1011, 308],
                "x": 957,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [504, 446, 612, 527],
                "x": 558,
                "y": 537,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [732, 296, 833, 401],
                "x": 782,
                "y": 403,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-3, 323, 103, 424],
                "x": 52,
                "y": 421,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [274, 328, 395, 433],
                "x": 343,
                "y": 426,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 617, "y": 460, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [574, 269, 694, 373],
                "x": 632,
                "y": 364,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [755, 472, 881, 560],
                "x": 812,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [349, 509, 450, 615],
                "x": 400,
                "y": 619,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [528, 21, 646, 107],
                "x": 588,
                "y": 112,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [900, 183, 1005, 285],
                "x": 955,
                "y": 283,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [512, 516, 619, 619],
                "x": 564,
                "y": 611,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [759, 293, 887, 401],
                "x": 826,
                "y": 396,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [-69, 194, 58, 304],
                "x": 0,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [304, 305, 416, 413],
                "x": 362,
                "y": 410,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [538, 377, 646, 481],
                "x": 595,
                "y": 477,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [543, 289, 675, 370],
                "x": 612,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [769, 454, 894, 559],
                "x": 829,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [308, 483, 433, 593],
                "x": 366,
                "y": 592,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [528, 17, 658, 112],
                "x": 598,
                "y": 121,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [898, 171, 1002, 272],
                "x": 952,
                "y": 267,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [511, 607, 629, 690],
                "x": 570,
                "y": 698,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 869, "y": 390, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [331, 302, 446, 397],
                "x": 381,
                "y": 392,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [511, 401, 628, 494],
                "x": 574,
                "y": 494,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [529, 304, 647, 405],
                "x": 591,
                "y": 395,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [782, 459, 903, 548],
                "x": 846,
                "y": 554,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 333, "y": 565, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 608, "y": 133, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [895, 145, 1003, 252],
                "x": 950,
                "y": 253,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [525, 708, 629, 795],
                "x": 576,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [853, 275, 963, 387],
                "x": 913,
                "y": 384,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [347, 277, 451, 378],
                "x": 401,
                "y": 373,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [485, 407, 620, 504],
                "x": 553,
                "y": 512,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [504, 317, 639, 410],
                "x": 571,
                "y": 414,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [795, 451, 932, 553],
                "x": 863,
                "y": 548,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [248, 430, 366, 545],
                "x": 300,
                "y": 537,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [556, 41, 688, 158],
                "x": 619,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [880, 128, 1009, 232],
                "x": 948,
                "y": 238,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [890, 284, 1025, 387],
                "x": 956,
                "y": 379,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [361, 256, 474, 343],
                "x": 420,
                "y": 353,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [471, 429, 582, 528],
                "x": 531,
                "y": 530,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 551, "y": 433, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [816, 446, 939, 551],
                "x": 880,
                "y": 544,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [197, 415, 318, 511],
                "x": 266,
                "y": 509,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [564, 67, 696, 175],
                "x": 629,
                "y": 170,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [877, 115, 1011, 228],
                "x": 945,
                "y": 224,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [939, 270, 1068, 380],
                "x": 1000,
                "y": 376,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [376, 239, 506, 328],
                "x": 439,
                "y": 333,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [457, 447, 563, 551],
                "x": 510,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [468, 345, 589, 451],
                "x": 530,
                "y": 454,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [841, 435, 947, 532],
                "x": 897,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [182, 392, 303, 478],
                "x": 233,
                "y": 483,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [582, 95, 704, 195],
                "x": 639,
                "y": 194,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [892, 107, 1007, 210],
                "x": 943,
                "y": 210,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [401, 209, 511, 310],
                "x": 458,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [435, 464, 551, 574],
                "x": 489,
                "y": 565,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [457, 368, 564, 483],
                "x": 510,
                "y": 475,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [853, 451, 977, 551],
                "x": 914,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [140, 363, 270, 449],
                "x": 200,
                "y": 457,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [594, 114, 712, 211],
                "x": 649,
                "y": 221,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [880, 97, 1005, 203],
                "x": 941,
                "y": 197,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 477, "y": 291, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [400, 477, 532, 575],
                "x": 468,
                "y": 581,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [425, 388, 539, 487],
                "x": 489,
                "y": 497,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [870, 442, 983, 538],
                "x": 931,
                "y": 547,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [110, 338, 232, 427],
                "x": 166,
                "y": 433,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 659, "y": 252, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [869, 88, 1007, 188],
                "x": 938,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [440, 163, 563, 279],
                "x": 496,
                "y": 269,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [395, 486, 509, 603],
                "x": 446,
                "y": 596,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 469, "y": 518, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [885, 446, 1000, 555],
                "x": 948,
                "y": 554,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [81, 303, 197, 410],
                "x": 133,
                "y": 411,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [612, 186, 734, 280],
                "x": 670,
                "y": 286,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [870, 63, 989, 174],
                "x": 936,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [457, 144, 570, 241],
                "x": 515,
                "y": 247,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [363, 513, 492, 606],
                "x": 425,
                "y": 610,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [390, 443, 513, 546],
                "x": 448,
                "y": 540,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [899, 458, 1031, 559],
                "x": 965,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [32, 282, 164, 393],
                "x": 99,
                "y": 392,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [626, 220, 747, 334],
                "x": 680,
                "y": 324,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [875, 55, 987, 155],
                "x": 934,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [472, 127, 597, 232],
                "x": 534,
                "y": 226,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [341, 520, 458, 629],
                "x": 404,
                "y": 622,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [374, 466, 490, 567],
                "x": 428,
                "y": 561,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [918, 474, 1042, 579],
                "x": 982,
                "y": 582,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-4, 284, 129, 373],
                "x": 66,
                "y": 377,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [631, 256, 754, 369],
                "x": 690,
                "y": 365,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [865, 45, 988, 157],
                "x": 931,
                "y": 147,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [484, 106, 616, 213],
                "x": 553,
                "y": 204,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 382, "y": 631, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [356, 478, 469, 580],
                "x": 408,
                "y": 581,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [935, 498, 1059, 610],
                "x": 1000,
                "y": 605,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-32, 269, 84, 360],
                "x": 33,
                "y": 365,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [637, 318, 754, 400],
                "x": 700,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [866, 25, 980, 137],
                "x": 929,
                "y": 135,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [521, 93, 623, 188],
                "x": 572,
                "y": 183,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 361, "y": 639, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [335, 491, 453, 601],
                "x": 387,
                "y": 599,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-68, 248, 51, 355],
                "x": 0,
                "y": 358,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [643, 347, 764, 464],
                "x": 710,
                "y": 456,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [876, 26, 977, 119],
                "x": 926,
                "y": 124,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [534, 68, 651, 162],
                "x": 591,
                "y": 162,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [284, 545, 404, 644],
                "x": 340,
                "y": 643,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [316, 525, 417, 616],
                "x": 367,
                "y": 616,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 721, "y": 507, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [865, 12, 979, 123],
                "x": 924,
                "y": 113,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [561, 50, 672, 150],
                "x": 611,
                "y": 141,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [257, 549, 372, 645],
                "x": 319,
                "y": 644,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [278, 522, 413, 641],
                "x": 346,
                "y": 632,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [673, 464, 781, 557],
                "x": 731,
                "y": 560,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [869, 1, 978, 102],
                "x": 922,
                "y": 102,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 630, "y": 122, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [228, 540, 356, 643],
                "x": 297,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [264, 550, 392, 641],
                "x": 326,
                "y": 645,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [674, 524, 794, 625],
                "x": 741,
                "y": 616,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [861, -4, 971, 95],
                "x": 919,
                "y": 92,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [599, 0, 705, 107],
                "x": 649,
                "y": 103,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [206, 530, 326, 625],
                "x": 276,
                "y": 635,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [251, 559, 372, 664],
                "x": 306,
                "y": 656,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 751, "y": 674, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [855, -11, 969, 85],
                "x": 917,
                "y": 82,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [612, -22, 735, 83],
                "x": 668,
                "y": 85,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [198, 524, 325, 627],
                "x": 255,
                "y": 625,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [223, 567, 339, 667],
                "x": 285,
                "y": 663,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [691, 626, 831, 741],
                "x": 761,
                "y": 736,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [860, -21, 980, 62],
                "x": 915,
                "y": 72,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [636, -35, 746, 75],
                "x": 687,
                "y": 68,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [169, 517, 285, 600],
                "x": 234,
                "y": 610,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [209, 566, 328, 661],
                "x": 265,
                "y": 668,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [710, 694, 833, 795],
                "x": 772,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [844, -29, 963, 59],
                "x": 912,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [643, -46, 758, 61],
                "x": 706,
                "y": 53,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [158, 485, 265, 596],
                "x": 212,
                "y": 590,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [182, 566, 308, 669],
                "x": 244,
                "y": 670,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [844, -45, 979, 55],
                "x": 910,
                "y": 54,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 725, "y": 39, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [130, 468, 250, 561],
                "x": 191,
                "y": 566,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [174, 558, 287, 662],
                "x": 224,
                "y": 667,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [838, -49, 961, 54],
                "x": 908,
                "y": 45,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [683, -76, 804, 22],
                "x": 744,
                "y": 26,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [105, 425, 225, 538],
                "x": 170,
                "y": 535,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [145, 563, 256, 658],
                "x": 204,
                "y": 661,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [849, -73, 965, 43],
                "x": 905,
                "y": 37,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [705, -86, 824, 19],
                "x": 763,
                "y": 15,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [94, 409, 200, 497],
                "x": 148,
                "y": 499,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [127, 558, 243, 659],
                "x": 183,
                "y": 650,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [845, -74, 963, 31],
                "x": 903,
                "y": 29,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [718, -92, 850, 11],
                "x": 782,
                "y": 7,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 127, "y": 457, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [106, 527, 229, 632],
                "x": 163,
                "y": 634,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [849, -89, 955, 23],
                "x": 901,
                "y": 21,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [743, -96, 853, -6],
                "x": 802,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [37, 317, 170, 398],
                "x": 106,
                "y": 408,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [90, 511, 209, 619],
                "x": 142,
                "y": 614,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [835, -82, 963, 11],
                "x": 898,
                "y": 14,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [28, 253, 152, 346],
                "x": 85,
                "y": 352,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [54, 489, 190, 584],
                "x": 122,
                "y": 588,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 1,
                "bounding_box": [833, -93, 948, -3],
                "x": 896,
                "y": 6,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [-2, 191, 121, 284],
                "x": 63,
                "y": 289,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [51, 451, 168, 566],
                "x": 102,
                "y": 556,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {"cb_id": 1, "bounding_box": [], "x": 894, "y": 0, "track_id": None},
            {"cb_id": 6, "bounding_box": [], "x": 42, "y": 219, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [15, 410, 131, 514],
                "x": 81,
                "y": 519,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 6,
                "bounding_box": [-38, 38, 75, 144],
                "x": 21,
                "y": 141,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-2, 366, 127, 469],
                "x": 61,
                "y": 475,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 48,
        "data": [
            {
                "cb_id": 6,
                "bounding_box": [-64, -37, 70, 63],
                "x": 0,
                "y": 55,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-20, 333, 92, 435],
                "x": 40,
                "y": 425,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 49,
        "data": [
            {
                "cb_id": 7,
                "bounding_box": [-40, 269, 81, 358],
                "x": 20,
                "y": 368,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 50,
        "data": [
            {
                "cb_id": 7,
                "bounding_box": [-66, 211, 56, 305],
                "x": 0,
                "y": 304,
                "track_id": None,
            }
        ],
    },
]
