country_balls_amount = 10
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [348, 702, 468, 797],
                "x": 407,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 75, "y": 0, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-56, 41, 62, 146],
                "x": 0,
                "y": 145,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [863, -98, 983, 0],
                "x": 924,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [942, 519, 1064, 609],
                "x": 1000,
                "y": 614,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [939, 167, 1060, 262],
                "x": 1000,
                "y": 265,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 943, "y": 0, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 1000, "y": 449, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [243, -103, 362, -2],
                "x": 307,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [803, -98, 924, 1],
                "x": 860,
                "y": 0,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [336, 693, 465, 802],
                "x": 400,
                "y": 797,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 72, "y": 12, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [-5, 209, 112, 316],
                "x": 52,
                "y": 313,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [861, -92, 983, 4],
                "x": 925,
                "y": 3,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [912, 528, 1035, 630],
                "x": 971,
                "y": 629,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [932, 154, 1055, 260],
                "x": 997,
                "y": 256,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 925, "y": 62, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [921, 396, 1041, 495],
                "x": 977,
                "y": 497,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 306, "y": 22, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [785, -85, 896, 12],
                "x": 841,
                "y": 13,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [331, 697, 456, 797],
                "x": 393,
                "y": 792,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [14, -78, 125, 29],
                "x": 70,
                "y": 25,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 105, "y": 437, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [871, -91, 992, 9],
                "x": 927,
                "y": 6,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [880, 538, 1005, 634],
                "x": 943,
                "y": 638,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [939, 143, 1057, 243],
                "x": 995,
                "y": 247,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [845, 22, 967, 124],
                "x": 908,
                "y": 119,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [899, 438, 1017, 544],
                "x": 954,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [247, -57, 370, 42],
                "x": 306,
                "y": 45,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 822, "y": 28, "track_id": None},
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 387, "y": 786, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [8, -57, 132, 43],
                "x": 68,
                "y": 39,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [99, 419, 213, 518],
                "x": 157,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [868, -87, 992, 9],
                "x": 929,
                "y": 10,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [857, 545, 969, 642],
                "x": 914,
                "y": 642,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 992, "y": 239, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [827, 66, 952, 170],
                "x": 891,
                "y": 171,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [873, 478, 989, 576],
                "x": 931,
                "y": 574,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 305, "y": 67, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 803, "y": 44, "track_id": None},
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [324, 679, 444, 776],
                "x": 380,
                "y": 779,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 66, "y": 53, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [149, 476, 266, 576],
                "x": 210,
                "y": 571,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [872, -86, 988, 10],
                "x": 931,
                "y": 13,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [831, 543, 948, 638],
                "x": 886,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [926, 126, 1046, 236],
                "x": 990,
                "y": 231,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [810, 113, 935, 218],
                "x": 874,
                "y": 216,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 909, "y": 604, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [245, -11, 370, 92],
                "x": 305,
                "y": 90,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 785, "y": 60, "track_id": None},
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [315, 673, 430, 770],
                "x": 374,
                "y": 770,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [5, -37, 128, 66],
                "x": 64,
                "y": 67,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [203, 495, 319, 588],
                "x": 263,
                "y": 590,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 932, "y": 17, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [798, 543, 921, 635],
                "x": 857,
                "y": 638,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 987, "y": 222, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [795, 161, 912, 255],
                "x": 857,
                "y": 257,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [822, 524, 945, 628],
                "x": 886,
                "y": 628,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [250, 9, 365, 117],
                "x": 305,
                "y": 112,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [709, -20, 824, 78],
                "x": 766,
                "y": 77,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [305, 656, 425, 754],
                "x": 367,
                "y": 759,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [1, -20, 119, 84],
                "x": 62,
                "y": 81,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [259, 481, 380, 581],
                "x": 315,
                "y": 585,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [870, -78, 992, 25],
                "x": 934,
                "y": 21,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 829, "y": 631, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [923, 115, 1047, 215],
                "x": 985,
                "y": 214,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 840, "y": 292, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [803, 543, 921, 647],
                "x": 863,
                "y": 646,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [244, 31, 359, 131],
                "x": 304,
                "y": 134,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 747, "y": 95, "track_id": None},
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [295, 650, 421, 752],
                "x": 360,
                "y": 748,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 60, "y": 96, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [303, 462, 430, 557],
                "x": 368,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [879, -77, 998, 22],
                "x": 936,
                "y": 25,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [742, 516, 864, 616],
                "x": 800,
                "y": 621,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [920, 108, 1037, 211],
                "x": 982,
                "y": 206,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [760, 218, 880, 318],
                "x": 823,
                "y": 321,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [781, 564, 897, 660],
                "x": 840,
                "y": 659,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 304, "y": 157, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 729, "y": 112, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [291, 640, 417, 731],
                "x": 354,
                "y": 735,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-4, 15, 113, 115],
                "x": 58,
                "y": 111,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [356, 415, 477, 513],
                "x": 421,
                "y": 518,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [883, -75, 1000, 26],
                "x": 938,
                "y": 28,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [715, 509, 831, 606],
                "x": 772,
                "y": 609,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [923, 100, 1045, 198],
                "x": 980,
                "y": 199,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 806, "y": 346, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [754, 566, 881, 672],
                "x": 818,
                "y": 668,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [244, 75, 361, 184],
                "x": 304,
                "y": 179,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [651, 33, 768, 129],
                "x": 710,
                "y": 131,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [287, 621, 406, 718],
                "x": 347,
                "y": 722,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-3, 25, 117, 131],
                "x": 56,
                "y": 126,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 473, "y": 467, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [882, -72, 996, 38],
                "x": 939,
                "y": 33,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [678, 493, 807, 599],
                "x": 743,
                "y": 596,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [920, 91, 1041, 194],
                "x": 978,
                "y": 191,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [733, 272, 850, 362],
                "x": 789,
                "y": 367,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 795, "y": 672, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [244, 104, 364, 206],
                "x": 303,
                "y": 201,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [629, 47, 755, 151],
                "x": 691,
                "y": 149,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [278, 607, 397, 707],
                "x": 341,
                "y": 708,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-2, 38, 109, 139],
                "x": 54,
                "y": 142,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [464, 308, 584, 412],
                "x": 526,
                "y": 410,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 941, "y": 37, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 715, "y": 581, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [918, 81, 1032, 182],
                "x": 975,
                "y": 184,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [710, 282, 836, 382],
                "x": 772,
                "y": 382,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [708, 573, 837, 669],
                "x": 772,
                "y": 672,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [244, 126, 364, 228],
                "x": 303,
                "y": 223,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [611, 70, 732, 162],
                "x": 673,
                "y": 167,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [272, 590, 389, 696],
                "x": 334,
                "y": 694,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-9, 57, 108, 155],
                "x": 52,
                "y": 158,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [519, 251, 637, 357],
                "x": 578,
                "y": 352,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 943, "y": 41, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 686, "y": 567, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 973, "y": 176, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [697, 291, 818, 393],
                "x": 755,
                "y": 394,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [689, 569, 813, 669],
                "x": 750,
                "y": 667,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [241, 143, 367, 244],
                "x": 303,
                "y": 246,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [593, 88, 714, 181],
                "x": 654,
                "y": 186,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [263, 575, 391, 685],
                "x": 327,
                "y": 680,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-7, 72, 106, 175],
                "x": 50,
                "y": 175,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [569, 196, 686, 296],
                "x": 631,
                "y": 298,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [889, -54, 1001, 43],
                "x": 945,
                "y": 45,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [595, 447, 713, 549],
                "x": 658,
                "y": 552,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 970, "y": 169, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [676, 306, 802, 398],
                "x": 738,
                "y": 401,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [672, 560, 784, 661],
                "x": 727,
                "y": 659,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [237, 166, 359, 272],
                "x": 302,
                "y": 268,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [571, 100, 697, 203],
                "x": 635,
                "y": 204,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 321, "y": 665, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 47, "y": 192, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [619, 157, 742, 251],
                "x": 684,
                "y": 254,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 946, "y": 50, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [567, 433, 688, 533],
                "x": 629,
                "y": 538,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [905, 60, 1031, 166],
                "x": 968,
                "y": 162,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 721, "y": 404, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 704, "y": 647, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 302, "y": 290, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [552, 124, 681, 224],
                "x": 616,
                "y": 222,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 314, "y": 650, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-18, 110, 110, 211],
                "x": 45,
                "y": 209,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 736, "y": 224, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [889, -45, 1007, 54],
                "x": 948,
                "y": 54,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [544, 425, 660, 526],
                "x": 601,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [900, 50, 1023, 153],
                "x": 965,
                "y": 155,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 704, "y": 403, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 681, "y": 633, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [243, 213, 361, 311],
                "x": 302,
                "y": 312,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [538, 136, 661, 244],
                "x": 598,
                "y": 240,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [247, 539, 365, 632],
                "x": 308,
                "y": 635,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-16, 122, 107, 223],
                "x": 43,
                "y": 226,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [728, 111, 851, 214],
                "x": 789,
                "y": 212,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [894, -37, 1005, 58],
                "x": 950,
                "y": 59,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 572, "y": 515, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [904, 53, 1021, 144],
                "x": 963,
                "y": 148,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [626, 297, 742, 393],
                "x": 687,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [600, 519, 715, 617],
                "x": 659,
                "y": 615,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 301, "y": 334, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [522, 162, 639, 260],
                "x": 579,
                "y": 257,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [236, 518, 363, 626],
                "x": 301,
                "y": 621,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-20, 140, 104, 241],
                "x": 41,
                "y": 244,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 842, "y": 224, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [893, -36, 1012, 59],
                "x": 952,
                "y": 63,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 544, "y": 507, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [899, 45, 1021, 136],
                "x": 961,
                "y": 141,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [611, 289, 729, 393],
                "x": 669,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [578, 498, 699, 597],
                "x": 636,
                "y": 594,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [242, 260, 358, 358],
                "x": 301,
                "y": 355,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [500, 174, 621, 270],
                "x": 560,
                "y": 274,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [239, 508, 355, 608],
                "x": 295,
                "y": 607,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-24, 162, 94, 259],
                "x": 39,
                "y": 263,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [830, 160, 956, 260],
                "x": 894,
                "y": 265,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 954, "y": 68, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [458, 407, 573, 504],
                "x": 515,
                "y": 502,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 958, "y": 135, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [592, 282, 714, 380],
                "x": 652,
                "y": 379,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 613, "y": 572, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [245, 278, 364, 379],
                "x": 301,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [482, 190, 601, 285],
                "x": 542,
                "y": 290,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [230, 489, 346, 593],
                "x": 288,
                "y": 594,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 37, "y": 281, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [888, 236, 1002, 339],
                "x": 947,
                "y": 339,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 955, "y": 73, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [432, 401, 543, 498],
                "x": 487,
                "y": 500,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [900, 31, 1020, 124],
                "x": 956,
                "y": 128,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 635, "y": 364, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 590, "y": 547, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [239, 294, 358, 403],
                "x": 300,
                "y": 399,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [466, 206, 584, 309],
                "x": 523,
                "y": 306,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [216, 476, 346, 576],
                "x": 281,
                "y": 581,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-21, 199, 91, 298],
                "x": 35,
                "y": 300,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 1000, "y": 451, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [894, -26, 1013, 79],
                "x": 957,
                "y": 78,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 458, "y": 502, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 953, "y": 122, "track_id": None},
            {
                "cb_id": 6,
                "bounding_box": [561, 243, 682, 351],
                "x": 618,
                "y": 346,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 568, "y": 520, "track_id": None},
            {"cb_id": 8, "bounding_box": [], "x": 300, "y": 421, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [448, 224, 569, 317],
                "x": 504,
                "y": 320,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [220, 469, 331, 565],
                "x": 275,
                "y": 569,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-28, 221, 89, 324],
                "x": 33,
                "y": 320,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 959, "y": 83, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [369, 409, 490, 510],
                "x": 430,
                "y": 509,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [892, 20, 1011, 117],
                "x": 951,
                "y": 115,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 601, "y": 326, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [482, 396, 605, 495],
                "x": 545,
                "y": 491,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [243, 342, 360, 439],
                "x": 299,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [422, 234, 542, 336],
                "x": 486,
                "y": 334,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [210, 462, 329, 558],
                "x": 268,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-34, 239, 94, 340],
                "x": 31,
                "y": 340,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [904, -13, 1022, 91],
                "x": 961,
                "y": 88,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [340, 423, 456, 524],
                "x": 401,
                "y": 521,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [892, 9, 1013, 104],
                "x": 948,
                "y": 109,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [521, 198, 640, 304],
                "x": 584,
                "y": 302,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [460, 360, 580, 466],
                "x": 522,
                "y": 462,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [234, 369, 355, 469],
                "x": 299,
                "y": 464,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 467, "y": 347, "track_id": None},
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [197, 450, 318, 547],
                "x": 262,
                "y": 549,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 29, "y": 360, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [904, -4, 1019, 94],
                "x": 962,
                "y": 94,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [309, 437, 433, 543],
                "x": 373,
                "y": 539,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [887, 2, 1006, 105],
                "x": 946,
                "y": 103,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [504, 178, 622, 281],
                "x": 567,
                "y": 276,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [445, 336, 559, 434],
                "x": 500,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [238, 390, 354, 480],
                "x": 299,
                "y": 485,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [386, 254, 510, 363],
                "x": 448,
                "y": 359,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [200, 441, 313, 540],
                "x": 255,
                "y": 541,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-31, 283, 87, 379],
                "x": 27,
                "y": 380,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [901, 3, 1028, 95],
                "x": 964,
                "y": 99,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 344, "y": 563, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [880, -1, 1003, 94],
                "x": 944,
                "y": 97,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [491, 151, 606, 253],
                "x": 550,
                "y": 248,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [422, 297, 539, 397],
                "x": 477,
                "y": 400,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 298, "y": 507, "track_id": None},
            {"cb_id": 9, "bounding_box": [], "x": 430, "y": 369, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 248, "y": 534, "track_id": None},
            {"cb_id": 1, "bounding_box": [], "x": 25, "y": 401, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [907, 7, 1024, 102],
                "x": 966,
                "y": 105,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [255, 490, 381, 600],
                "x": 316,
                "y": 595,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [881, -8, 1002, 91],
                "x": 941,
                "y": 92,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [470, 119, 593, 217],
                "x": 533,
                "y": 218,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [393, 270, 518, 367],
                "x": 454,
                "y": 368,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [241, 426, 355, 531],
                "x": 298,
                "y": 528,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 411, "y": 378, "track_id": None},
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [185, 431, 301, 525],
                "x": 242,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-42, 322, 79, 419],
                "x": 22,
                "y": 423,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [907, 15, 1030, 111],
                "x": 968,
                "y": 110,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [228, 536, 344, 631],
                "x": 287,
                "y": 633,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [880, -17, 1000, 81],
                "x": 939,
                "y": 86,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 516, "y": 185, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 431, "y": 336, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [233, 448, 353, 552],
                "x": 298,
                "y": 549,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [334, 283, 448, 387],
                "x": 392,
                "y": 386,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [172, 427, 299, 524],
                "x": 235,
                "y": 526,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-37, 344, 80, 441],
                "x": 20,
                "y": 444,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [906, 13, 1027, 116],
                "x": 969,
                "y": 116,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [200, 576, 320, 676],
                "x": 259,
                "y": 680,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [875, -18, 994, 76],
                "x": 936,
                "y": 80,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [434, 49, 564, 153],
                "x": 499,
                "y": 151,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [346, 207, 467, 303],
                "x": 409,
                "y": 303,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 297, "y": 571, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [316, 287, 428, 389],
                "x": 373,
                "y": 392,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [169, 426, 294, 528],
                "x": 229,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-44, 362, 83, 461],
                "x": 18,
                "y": 466,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [912, 25, 1032, 125],
                "x": 971,
                "y": 122,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [170, 639, 289, 737],
                "x": 230,
                "y": 735,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [870, -26, 994, 72],
                "x": 934,
                "y": 75,
                "track_id": None,
            },
            {"cb_id": 6, "bounding_box": [], "x": 482, "y": 115, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [325, 170, 451, 269],
                "x": 386,
                "y": 272,
                "track_id": None,
            },
            {"cb_id": 8, "bounding_box": [], "x": 297, "y": 592, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [299, 295, 420, 395],
                "x": 355,
                "y": 397,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [162, 427, 278, 522],
                "x": 222,
                "y": 526,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 16, "y": 489, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 973, "y": 128, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [140, 697, 267, 805],
                "x": 202,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [875, -26, 988, 69],
                "x": 931,
                "y": 70,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [400, -27, 520, 78],
                "x": 465,
                "y": 78,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [304, 138, 419, 244],
                "x": 363,
                "y": 241,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [237, 518, 361, 616],
                "x": 297,
                "y": 613,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [272, 296, 400, 405],
                "x": 336,
                "y": 400,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [153, 431, 280, 532],
                "x": 216,
                "y": 529,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-41, 410, 76, 507],
                "x": 14,
                "y": 512,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 975, "y": 134, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [870, -38, 992, 62],
                "x": 929,
                "y": 64,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [384, -59, 511, 34],
                "x": 448,
                "y": 39,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 340, "y": 210, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [231, 529, 355, 630],
                "x": 296,
                "y": 634,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [262, 305, 378, 405],
                "x": 317,
                "y": 401,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [147, 434, 273, 533],
                "x": 209,
                "y": 535,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-53, 431, 70, 530],
                "x": 12,
                "y": 535,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [920, 36, 1039, 143],
                "x": 977,
                "y": 140,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [868, -45, 986, 62],
                "x": 927,
                "y": 59,
                "track_id": None,
            },
            {
                "cb_id": 6,
                "bounding_box": [366, -103, 489, 5],
                "x": 431,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [263, 79, 380, 179],
                "x": 318,
                "y": 181,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [240, 560, 354, 660],
                "x": 296,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [242, 297, 359, 403],
                "x": 299,
                "y": 401,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [145, 443, 260, 538],
                "x": 202,
                "y": 543,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-50, 459, 65, 562],
                "x": 10,
                "y": 559,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [918, 46, 1037, 141],
                "x": 978,
                "y": 146,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [867, -43, 986, 55],
                "x": 924,
                "y": 54,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [235, 59, 359, 153],
                "x": 295,
                "y": 154,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [236, 572, 360, 671],
                "x": 296,
                "y": 676,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [220, 302, 335, 393],
                "x": 280,
                "y": 398,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 196, "y": 554, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [-54, 485, 65, 587],
                "x": 8,
                "y": 583,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [917, 52, 1038, 150],
                "x": 980,
                "y": 152,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [858, -47, 986, 48],
                "x": 922,
                "y": 49,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [213, 29, 327, 126],
                "x": 272,
                "y": 128,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [234, 595, 351, 694],
                "x": 295,
                "y": 697,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [204, 294, 324, 395],
                "x": 261,
                "y": 393,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [130, 467, 249, 569],
                "x": 189,
                "y": 567,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 6, "y": 607, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [920, 55, 1038, 161],
                "x": 982,
                "y": 159,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [857, -52, 979, 41],
                "x": 919,
                "y": 45,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [192, 7, 305, 100],
                "x": 250,
                "y": 104,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [236, 621, 359, 717],
                "x": 295,
                "y": 717,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 243, "y": 386, "track_id": None},
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [121, 489, 244, 582],
                "x": 183,
                "y": 584,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-53, 527, 67, 633],
                "x": 4,
                "y": 632,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 984, "y": 165, "track_id": None},
            {"cb_id": 5, "bounding_box": [], "x": 917, "y": 40, "track_id": None},
            {"cb_id": 7, "bounding_box": [], "x": 227, "y": 82, "track_id": None},
            {
                "cb_id": 8,
                "bounding_box": [232, 642, 355, 734],
                "x": 295,
                "y": 738,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [164, 276, 282, 373],
                "x": 224,
                "y": 377,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [113, 502, 236, 604],
                "x": 176,
                "y": 604,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-63, 556, 61, 653],
                "x": 2,
                "y": 658,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [922, 68, 1049, 175],
                "x": 985,
                "y": 172,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [851, -59, 973, 33],
                "x": 914,
                "y": 36,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [142, -37, 266, 65],
                "x": 204,
                "y": 63,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [233, 656, 350, 757],
                "x": 294,
                "y": 759,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [142, 263, 260, 360],
                "x": 205,
                "y": 365,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [107, 524, 233, 629],
                "x": 169,
                "y": 628,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [-63, 580, 56, 684],
                "x": 0,
                "y": 684,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [931, 83, 1043, 177],
                "x": 987,
                "y": 179,
                "track_id": None,
            },
            {"cb_id": 5, "bounding_box": [], "x": 912, "y": 31, "track_id": None},
            {
                "cb_id": 7,
                "bounding_box": [121, -50, 242, 45],
                "x": 181,
                "y": 47,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [231, 674, 355, 783],
                "x": 294,
                "y": 779,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [126, 251, 242, 351],
                "x": 186,
                "y": 351,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 163, "y": 654, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [934, 81, 1050, 190],
                "x": 989,
                "y": 186,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [848, -68, 971, 29],
                "x": 910,
                "y": 27,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [99, -68, 215, 29],
                "x": 159,
                "y": 33,
                "track_id": None,
            },
            {
                "cb_id": 8,
                "bounding_box": [229, 697, 352, 803],
                "x": 294,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 9, "bounding_box": [], "x": 168, "y": 334, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [95, 580, 215, 688],
                "x": 156,
                "y": 685,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [934, 89, 1046, 191],
                "x": 991,
                "y": 193,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [846, -76, 968, 19],
                "x": 907,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [79, -81, 191, 21],
                "x": 136,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [89, 215, 205, 313],
                "x": 149,
                "y": 315,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [94, 623, 206, 724],
                "x": 150,
                "y": 719,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [936, 97, 1051, 200],
                "x": 992,
                "y": 200,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [840, -82, 968, 19],
                "x": 905,
                "y": 18,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [56, -78, 175, 20],
                "x": 113,
                "y": 17,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [75, 190, 192, 288],
                "x": 130,
                "y": 293,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [81, 658, 202, 755],
                "x": 143,
                "y": 757,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [938, 102, 1055, 210],
                "x": 994,
                "y": 207,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [843, -84, 958, 9],
                "x": 902,
                "y": 14,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [27, -83, 153, 20],
                "x": 90,
                "y": 15,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [50, 163, 174, 273],
                "x": 112,
                "y": 268,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [74, 698, 192, 795],
                "x": 137,
                "y": 800,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [939, 114, 1054, 209],
                "x": 996,
                "y": 214,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [843, -87, 965, 9],
                "x": 900,
                "y": 11,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [5, -82, 133, 20],
                "x": 68,
                "y": 16,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [36, 139, 157, 235],
                "x": 93,
                "y": 239,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {"cb_id": 3, "bounding_box": [], "x": 998, "y": 222, "track_id": None},
            {
                "cb_id": 5,
                "bounding_box": [832, -93, 960, 4],
                "x": 897,
                "y": 7,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-16, -73, 106, 22],
                "x": 45,
                "y": 23,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [13, 111, 130, 204],
                "x": 74,
                "y": 208,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 3,
                "bounding_box": [941, 130, 1065, 228],
                "x": 1000,
                "y": 230,
                "track_id": None,
            },
            {
                "cb_id": 5,
                "bounding_box": [831, -95, 953, 5],
                "x": 895,
                "y": 3,
                "track_id": None,
            },
            {"cb_id": 7, "bounding_box": [], "x": 22, "y": 34, "track_id": None},
            {
                "cb_id": 9,
                "bounding_box": [-3, 78, 120, 179],
                "x": 56,
                "y": 174,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 5,
                "bounding_box": [831, -100, 952, -3],
                "x": 893,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 7,
                "bounding_box": [-58, -46, 58, 49],
                "x": 0,
                "y": 50,
                "track_id": None,
            },
            {
                "cb_id": 9,
                "bounding_box": [-25, 32, 94, 136],
                "x": 37,
                "y": 136,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 9,
                "bounding_box": [-46, -7, 74, 93],
                "x": 18,
                "y": 95,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [
            {
                "cb_id": 9,
                "bounding_box": [-55, -54, 61, 47],
                "x": 0,
                "y": 51,
                "track_id": None,
            }
        ],
    },
]
