country_balls_amount = 5
track_data = [
    {
        "frame_id": 1,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-52, 150, 52, 263],
                "x": 0,
                "y": 259,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [728, 690, 851, 803],
                "x": 793,
                "y": 799,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 956, "y": 0, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [937, 288, 1058, 397],
                "x": 1000,
                "y": 397,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 886, "y": 0, "track_id": None},
        ],
    },
    {
        "frame_id": 2,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [-29, 218, 81, 329],
                "x": 25,
                "y": 320,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [696, 502, 834, 603],
                "x": 764,
                "y": 597,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 957, "y": 13, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 998, "y": 380, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [809, -55, 917, 34],
                "x": 866,
                "y": 44,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 3,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 51, "y": 375, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [676, 346, 797, 456],
                "x": 735,
                "y": 450,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [907, -76, 1008, 29],
                "x": 958,
                "y": 27,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 996, "y": 363, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [796, -22, 907, 77],
                "x": 847,
                "y": 85,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 4,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [20, 328, 140, 415],
                "x": 76,
                "y": 424,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [649, 261, 776, 354],
                "x": 707,
                "y": 352,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 959, "y": 42, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [942, 237, 1062, 337],
                "x": 995,
                "y": 347,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [771, 15, 881, 125],
                "x": 828,
                "y": 124,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 5,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [45, 375, 167, 473],
                "x": 102,
                "y": 467,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [615, 207, 731, 299],
                "x": 678,
                "y": 297,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [891, -44, 1014, 53],
                "x": 961,
                "y": 56,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [934, 236, 1056, 333],
                "x": 993,
                "y": 331,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [747, 53, 866, 150],
                "x": 808,
                "y": 160,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 6,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [60, 410, 185, 512],
                "x": 128,
                "y": 504,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [593, 171, 705, 280],
                "x": 649,
                "y": 279,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [911, -37, 1020, 68],
                "x": 962,
                "y": 71,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 992, "y": 315, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [719, 100, 839, 197],
                "x": 789,
                "y": 193,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 7,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [100, 436, 215, 544],
                "x": 153,
                "y": 536,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 621, "y": 291, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [907, -13, 1020, 90],
                "x": 963,
                "y": 87,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [927, 210, 1057, 291],
                "x": 990,
                "y": 300,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [720, 132, 829, 228],
                "x": 770,
                "y": 224,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 8,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [121, 460, 245, 558],
                "x": 179,
                "y": 562,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 592, "y": 326, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [909, 1, 1027, 105],
                "x": 965,
                "y": 102,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [939, 178, 1039, 284],
                "x": 989,
                "y": 285,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 751, "y": 252, "track_id": None},
        ],
    },
    {
        "frame_id": 9,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [143, 488, 259, 587],
                "x": 205,
                "y": 584,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [499, 284, 629, 376],
                "x": 563,
                "y": 378,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [907, 23, 1033, 111],
                "x": 966,
                "y": 118,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 987, "y": 270, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [661, 186, 794, 281],
                "x": 731,
                "y": 278,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 10,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [180, 510, 280, 608],
                "x": 230,
                "y": 601,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [479, 344, 598, 446],
                "x": 535,
                "y": 442,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [911, 40, 1023, 130],
                "x": 967,
                "y": 135,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [928, 160, 1042, 253],
                "x": 986,
                "y": 256,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [659, 210, 781, 292],
                "x": 712,
                "y": 301,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 11,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [200, 522, 306, 623],
                "x": 256,
                "y": 614,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 506, "y": 509, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 968, "y": 151, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [928, 134, 1043, 237],
                "x": 984,
                "y": 242,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [624, 212, 749, 332],
                "x": 693,
                "y": 322,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 12,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [217, 527, 338, 633],
                "x": 282,
                "y": 623,
                "track_id": None,
            },
            {"cb_id": 1, "bounding_box": [], "x": 477, "y": 574, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [913, 74, 1037, 162],
                "x": 970,
                "y": 168,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [927, 121, 1038, 223],
                "x": 983,
                "y": 228,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [615, 246, 727, 332],
                "x": 674,
                "y": 340,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 13,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [253, 535, 359, 637],
                "x": 307,
                "y": 629,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [399, 533, 508, 628],
                "x": 449,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [917, 86, 1032, 186],
                "x": 971,
                "y": 185,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [916, 109, 1047, 205],
                "x": 981,
                "y": 214,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [587, 266, 714, 356],
                "x": 654,
                "y": 357,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 14,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [282, 530, 388, 630],
                "x": 333,
                "y": 631,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [369, 569, 486, 669],
                "x": 420,
                "y": 672,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 972, "y": 203, "track_id": None},
            {"cb_id": 3, "bounding_box": [], "x": 980, "y": 201, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 635, "y": 371, "track_id": None},
        ],
    },
    {
        "frame_id": 15,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [290, 527, 423, 634],
                "x": 358,
                "y": 629,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [326, 589, 452, 682],
                "x": 391,
                "y": 692,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [909, 120, 1040, 231],
                "x": 974,
                "y": 221,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [928, 94, 1036, 185],
                "x": 978,
                "y": 188,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [557, 279, 668, 383],
                "x": 616,
                "y": 383,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 16,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [327, 526, 451, 628],
                "x": 384,
                "y": 625,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [304, 578, 420, 693],
                "x": 363,
                "y": 684,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [921, 130, 1028, 245],
                "x": 975,
                "y": 239,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 977, "y": 175, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [532, 295, 650, 391],
                "x": 597,
                "y": 393,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 17,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [360, 521, 471, 617],
                "x": 410,
                "y": 619,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [280, 544, 392, 639],
                "x": 334,
                "y": 642,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [917, 159, 1040, 249],
                "x": 976,
                "y": 258,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [921, 68, 1039, 171],
                "x": 975,
                "y": 163,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [517, 308, 642, 400],
                "x": 577,
                "y": 401,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 18,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 435, "y": 610, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [236, 464, 363, 559],
                "x": 305,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [927, 180, 1042, 280],
                "x": 978,
                "y": 277,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [916, 57, 1026, 143],
                "x": 973,
                "y": 150,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [491, 314, 624, 399],
                "x": 558,
                "y": 407,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 19,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 461, "y": 599, "track_id": None},
            {
                "cb_id": 1,
                "bounding_box": [213, 326, 346, 419],
                "x": 277,
                "y": 428,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [929, 193, 1040, 302],
                "x": 979,
                "y": 296,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [917, 45, 1032, 149],
                "x": 972,
                "y": 139,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [482, 302, 596, 418],
                "x": 539,
                "y": 412,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 20,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [421, 493, 547, 593],
                "x": 487,
                "y": 587,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [193, 135, 316, 241],
                "x": 248,
                "y": 244,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 980, "y": 316, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [913, 36, 1023, 120],
                "x": 970,
                "y": 127,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 520, "y": 414, "track_id": None},
        ],
    },
    {
        "frame_id": 21,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [458, 465, 579, 576],
                "x": 512,
                "y": 573,
                "track_id": None,
            },
            {
                "cb_id": 1,
                "bounding_box": [169, -106, 285, -7],
                "x": 220,
                "y": 0,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 981, "y": 336, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [900, 21, 1029, 121],
                "x": 969,
                "y": 116,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 500, "y": 415, "track_id": None},
        ],
    },
    {
        "frame_id": 22,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [482, 455, 595, 553],
                "x": 538,
                "y": 558,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [917, 249, 1041, 350],
                "x": 983,
                "y": 356,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 967, "y": 104, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [429, 320, 535, 417],
                "x": 481,
                "y": 414,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 23,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [496, 448, 623, 532],
                "x": 564,
                "y": 542,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [934, 273, 1035, 372],
                "x": 984,
                "y": 377,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [899, -12, 1030, 94],
                "x": 966,
                "y": 94,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [392, 307, 521, 416],
                "x": 462,
                "y": 411,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 24,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [532, 424, 656, 523],
                "x": 589,
                "y": 525,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [933, 292, 1054, 405],
                "x": 985,
                "y": 398,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [905, -9, 1015, 81],
                "x": 964,
                "y": 83,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 443, "y": 407, "track_id": None},
        ],
    },
    {
        "frame_id": 25,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [560, 402, 684, 514],
                "x": 615,
                "y": 509,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 987, "y": 420, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [902, -22, 1032, 67],
                "x": 963,
                "y": 73,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [372, 300, 475, 399],
                "x": 423,
                "y": 402,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 26,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [573, 395, 707, 487],
                "x": 641,
                "y": 492,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [931, 348, 1052, 437],
                "x": 988,
                "y": 441,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 961, "y": 63, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [340, 293, 461, 399],
                "x": 404,
                "y": 395,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 27,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [610, 370, 721, 485],
                "x": 666,
                "y": 476,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 989, "y": 464, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [907, -55, 1022, 59],
                "x": 960,
                "y": 53,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [320, 277, 445, 384],
                "x": 385,
                "y": 386,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 28,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [626, 358, 749, 455],
                "x": 692,
                "y": 460,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [925, 381, 1040, 479],
                "x": 990,
                "y": 486,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [904, -57, 1016, 53],
                "x": 958,
                "y": 43,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [315, 272, 429, 379],
                "x": 365,
                "y": 376,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 29,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [661, 339, 783, 439],
                "x": 717,
                "y": 445,
                "track_id": None,
            },
            {"cb_id": 2, "bounding_box": [], "x": 992, "y": 509, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [898, -62, 1007, 31],
                "x": 957,
                "y": 34,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [282, 261, 396, 365],
                "x": 346,
                "y": 365,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 30,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [689, 324, 793, 424],
                "x": 743,
                "y": 431,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [932, 422, 1049, 524],
                "x": 993,
                "y": 532,
                "track_id": None,
            },
            {"cb_id": 3, "bounding_box": [], "x": 955, "y": 25, "track_id": None},
            {"cb_id": 4, "bounding_box": [], "x": 327, "y": 353, "track_id": None},
        ],
    },
    {
        "frame_id": 31,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 769, "y": 419, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 994, "y": 556, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [889, -78, 1006, 20],
                "x": 954,
                "y": 16,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [251, 247, 367, 349],
                "x": 308,
                "y": 340,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 32,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [744, 301, 848, 415],
                "x": 794,
                "y": 409,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [944, 475, 1057, 576],
                "x": 996,
                "y": 580,
                "track_id": None,
            },
            {
                "cb_id": 3,
                "bounding_box": [885, -95, 1019, 10],
                "x": 952,
                "y": 8,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [235, 229, 354, 317],
                "x": 288,
                "y": 325,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 33,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 820, "y": 400, "track_id": None},
            {"cb_id": 2, "bounding_box": [], "x": 997, "y": 604, "track_id": None},
            {
                "cb_id": 3,
                "bounding_box": [899, -93, 1013, -3],
                "x": 951,
                "y": 0,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [213, 202, 325, 303],
                "x": 269,
                "y": 310,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 34,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 846, "y": 394, "track_id": None},
            {
                "cb_id": 2,
                "bounding_box": [948, 530, 1058, 626],
                "x": 998,
                "y": 629,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [194, 197, 304, 287],
                "x": 250,
                "y": 293,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 35,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [813, 282, 926, 400],
                "x": 871,
                "y": 391,
                "track_id": None,
            },
            {
                "cb_id": 2,
                "bounding_box": [944, 558, 1055, 657],
                "x": 1000,
                "y": 655,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [181, 170, 293, 267],
                "x": 231,
                "y": 276,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 36,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [841, 298, 966, 392],
                "x": 897,
                "y": 390,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [148, 165, 269, 260],
                "x": 211,
                "y": 258,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 37,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [855, 301, 987, 392],
                "x": 923,
                "y": 393,
                "track_id": None,
            },
            {
                "cb_id": 4,
                "bounding_box": [134, 139, 260, 248],
                "x": 192,
                "y": 239,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 38,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [890, 295, 1010, 401],
                "x": 948,
                "y": 399,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 173, "y": 219, "track_id": None},
        ],
    },
    {
        "frame_id": 39,
        "data": [
            {
                "cb_id": 0,
                "bounding_box": [919, 314, 1027, 401],
                "x": 974,
                "y": 409,
                "track_id": None,
            },
            {"cb_id": 4, "bounding_box": [], "x": 154, "y": 199, "track_id": None},
        ],
    },
    {
        "frame_id": 40,
        "data": [
            {"cb_id": 0, "bounding_box": [], "x": 1000, "y": 423, "track_id": None},
            {
                "cb_id": 4,
                "bounding_box": [78, 82, 204, 172],
                "x": 134,
                "y": 178,
                "track_id": None,
            },
        ],
    },
    {
        "frame_id": 41,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [54, 59, 166, 156],
                "x": 115,
                "y": 156,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 42,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [46, 28, 166, 129],
                "x": 96,
                "y": 134,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 43,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [13, 14, 138, 120],
                "x": 77,
                "y": 112,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 44,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [1, -11, 107, 94],
                "x": 57,
                "y": 89,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 45,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [-23, -34, 99, 62],
                "x": 38,
                "y": 66,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 46,
        "data": [
            {
                "cb_id": 4,
                "bounding_box": [-43, -52, 82, 50],
                "x": 19,
                "y": 43,
                "track_id": None,
            }
        ],
    },
    {
        "frame_id": 47,
        "data": [{"cb_id": 4, "bounding_box": [], "x": 0, "y": 20, "track_id": None}],
    },
]
